require("colorbuddy").colorscheme("gruvbuddy")
local colorbuddy = require("colorbuddy")
local Color = colorbuddy.Color
local Group = colorbuddy.Group
local c = colorbuddy.colors
local s = colorbuddy.styles

Color.new("base", "#0a0a0a")
Color.new("surface", "#1a1a1a")
Color.new("overlay", "#2a2a2a")
Color.new("muted", "#6a6a6a")
Color.new("subtle", "#9a9a9a")
Color.new("text", "#f0f0f0")
Color.new("love", "#d946ef")
Color.new("gold", "#e9d5ff")
Color.new("rose", "#c084fc")
Color.new("pine", "#a855f7")
Color.new("foam", "#e0e0e0")
Color.new("iris", "#9333ea")
Color.new("highlight_low", "#151515")
Color.new("highlight_med", "#353535")
Color.new("highlight_high", "#4a4a4a")
Color.new("none", "NONE")

Group.new("Normal", c.text, c.none)

Group.new("Cursor", c.base, c.text)
Group.new("CursorLine", nil, c.highlight_low)
Group.new("CursorColumn", nil, c.highlight_low)
Group.new("CursorLineNr", c.iris, nil)
Group.new("LineNr", c.highlight_med, nil)
Group.new("LineNrAbove", c.subtle, nil)
Group.new("LineNrBelow", c.subtle, nil)
Group.new("ColorColumn", nil, c.highlight_low)
Group.new("SignColumn", nil, c.base)

Group.new("VertSplit", c.highlight_med, c.base)
Group.new("WinSeparator", c.highlight_med, c.base)

Group.new("Visual", nil, c.highlight_med)
Group.new("VisualNOS", nil, c.highlight_med)

Group.new("Search", c.base, c.gold)
Group.new("IncSearch", c.base, c.foam)
Group.new("CurSearch", c.base, c.rose)
Group.new("Substitute", c.base, c.pine)

Group.new("StatusLine", c.text, c.surface)
Group.new("StatusLineNC", c.subtle, c.surface)
Group.new("TabLine", c.subtle, c.surface)
Group.new("TabLineFill", nil, c.surface)
Group.new("TabLineSel", c.text, c.overlay)

Group.new("Pmenu", c.text, c.overlay)
Group.new("PmenuSel", c.overlay, c.iris)
Group.new("PmenuSbar", nil, c.overlay)
Group.new("PmenuThumb", nil, c.highlight_high)
Group.new("PmenuKind", c.foam, c.overlay)
Group.new("PmenuKindSel", c.overlay, c.iris)
Group.new("PmenuExtra", c.subtle, c.overlay)
Group.new("PmenuExtraSel", c.overlay, c.iris)

Group.new("ErrorMsg", c.love, c.base, s.bold)
Group.new("WarningMsg", c.gold, c.base, s.bold)
Group.new("ModeMsg", c.foam, c.base)
Group.new("MoreMsg", c.iris, c.base)
Group.new("Question", c.gold, c.base)

Group.new("Directory", c.foam, nil, s.bold)
Group.new("Title", c.iris, nil, s.bold)
Group.new("NonText", c.muted, nil)
Group.new("EndOfBuffer", c.base, nil)
Group.new("SpecialKey", c.foam, nil)
Group.new("MatchParen", c.text, c.highlight_high, s.bold)
Group.new("Conceal", c.subtle, nil)
Group.new("Whitespace", c.highlight_med, nil)

Group.new("Comment", c.muted, nil)
Group.new("Todo", c.iris, c.highlight_low, s.bold)

Group.new("String", c.gold, nil)
Group.new("Character", c.gold, nil)
Group.new("Number", c.gold, nil)
Group.new("Boolean", c.rose, nil)
Group.new("Float", c.gold, nil)
Group.new("Constant", c.rose, nil)

Group.new("Identifier", c.text, nil)
Group.new("Function", c.rose, nil)

Group.new("Statement", c.pine, nil)
Group.new("Conditional", c.pine, nil)
Group.new("Repeat", c.pine, nil)
Group.new("Label", c.pine, nil)
Group.new("Operator", c.pine, nil)
Group.new("Keyword", c.pine, nil)
Group.new("Exception", c.pine, nil)

Group.new("PreProc", c.iris, nil)
Group.new("Include", c.iris, nil)
Group.new("Define", c.iris, nil)
Group.new("Macro", c.iris, nil)
Group.new("PreCondit", c.iris, nil)

Group.new("Type", c.foam, nil)
Group.new("StorageClass", c.foam, nil)
Group.new("Structure", c.foam, nil)
Group.new("Typedef", c.foam, nil)

Group.new("Special", c.rose, nil)
Group.new("SpecialChar", c.rose, nil)
Group.new("Tag", c.foam, nil)
Group.new("Delimiter", c.subtle, nil)
Group.new("SpecialComment", c.iris, nil)
Group.new("Debug", c.rose, nil)

Group.new("Underlined", c.foam, nil, s.underline)
Group.new("Error", c.love, c.base, s.bold)
