require("colorbuddy").colorscheme("gruvbuddy")
local colorbuddy = require("colorbuddy")
local Color = colorbuddy.Color
local Group = colorbuddy.Group
local c = colorbuddy.colors
local s = colorbuddy.styles

Color.new("white", "#f2e5bc")
Color.new("red", "#cc6666")
Color.new("pink", "#fef601")
Color.new("green", "#99cc99")
Color.new("yellow", "#f8fe7a")
Color.new("blue", "#81a2be")
Color.new("light_blue", "#90D5FF")
Color.new("aqua", "#8ec07c")
Color.new("cyan", "#8abeb7")
Color.new("purple", "#b294bb")
Color.new("violet", "#b294bb")
Color.new("orange", "#de935f")
Color.new("brown", "#a3685a")
Color.new("seagreen", "#698b69")
Color.new("turquoise", "#698b69")

local background_string = "#000000"
Color.new("background", background_string)
Color.new("gray0", background_string)

Color.new("bg_light", "#1a1a1a")
Color.new("bg_lighter", "#252525")
Color.new("gray_dim", "#3a3a3a")
Color.new("gray_medium", "#505050")

Group.new("Normal", c.superwhite, c.gray0)

Group.new("NormalFloat", c.superwhite, c.gray0)
Group.new("FloatBorder", c.blue, c.gray0)
Group.new("FloatTitle", c.yellow, c.gray0, s.bold)
Group.new("Cursor", c.gray0, c.superwhite)
Group.new("CursorLine", nil, c.bg_light)
Group.new("CursorColumn", nil, c.bg_light)
Group.new("CursorLineNr", c.yellow, c.gray0, s.bold)
Group.new("LineNr", c.yellow, c.gray0, s.bold)
Group.new("LineNrAbove", c.gray_medium, c.gray0)
Group.new("LineNrBelow", c.gray_medium, c.gray0)
Group.new("ColorColumn", nil, c.bg_light)
Group.new("SignColumn", nil, c.gray0)
Group.new("VertSplit", c.gray_dim, c.gray0)
Group.new("WinSeparator", c.gray_dim, c.gray0)

Group.new("Visual", nil, c.bg_lighter)
Group.new("VisualNOS", nil, c.bg_lighter)

Group.new("Search", c.gray0, c.yellow)
Group.new("IncSearch", c.gray0, c.orange)
Group.new("CurSearch", c.gray0, c.pink)
Group.new("Substitute", c.gray0, c.green)

Group.new("StatusLine", c.gray0, c.light_blue)
Group.new("StatusLineNC", c.gray0, c.light_blue)
Group.new("TabLine", c.gray_medium, c.bg_light)
Group.new("TabLineFill", nil, c.bg_light)
Group.new("TabLineSel", c.superwhite, c.bg_lighter, s.bold)

Group.new("Pmenu", c.superwhite, c.gray0)
Group.new("PmenuSel", c.gray0, c.yellow, s.bold)
Group.new("PmenuSbar", nil, c.gray0)
Group.new("PmenuThumb", nil, c.gray0)
Group.new("PmenuKind", c.orange, c.gray0)
Group.new("PmenuKindSel", c.gray0, c.yellow)
Group.new("PmenuExtra", c.blue, c.gray0)
Group.new("PmenuExtraSel", c.gray0, c.yellow)

Group.new("DiffAdd", c.green, c.bg_light)
Group.new("DiffChange", c.blue, c.bg_light)
Group.new("DiffDelete", c.red, c.bg_light)
Group.new("DiffText", c.yellow, c.bg_lighter, s.bold)

Group.new("ErrorMsg", c.red, nil, s.bold)
Group.new("WarningMsg", c.orange, nil, s.bold)
Group.new("ModeMsg", c.yellow, nil, s.bold)
Group.new("MoreMsg", c.green, nil, s.bold)
Group.new("Question", c.blue, nil, s.bold)

Group.new("Directory", c.blue, nil, s.bold)
Group.new("Title", c.orange, nil, s.bold)
Group.new("NonText", c.purple, nil, s.italic)
Group.new("EndOfBuffer", c.bg_light, nil)
Group.new("SpecialKey", c.purple, nil)
Group.new("MatchParen", c.pink, c.bg_lighter, s.bold)
Group.new("Conceal", c.blue, nil, s.italic)
Group.new("Whitespace", c.purple, nil)

Group.new("Comment", c.yellow, nil, s.italic)
Group.new("Todo", c.pink, c.gray0, s.bold)
Group.new("String", c.green, nil)
Group.new("Character", c.green, nil)
Group.new("Number", c.orange, nil)
Group.new("Boolean", c.orange, nil)
Group.new("Float", c.orange, nil)
Group.new("Identifier", c.superwhite, nil)
Group.new("Statement", c.violet, nil, s.none)
Group.new("Conditional", c.violet, nil)
Group.new("Repeat", c.violet, nil)
Group.new("Label", c.violet, nil)
Group.new("Operator", c.violet, nil)
Group.new("Keyword", c.violet, nil, s.none)
Group.new("Exception", c.red, nil)
Group.new("PreProc", c.cyan, nil)
Group.new("Include", c.cyan, nil)
Group.new("Define", c.cyan, nil)
Group.new("Macro", c.cyan, nil)
Group.new("Type", c.yellow, nil, s.italic)
Group.new("StorageClass", c.violet, nil)
Group.new("Structure", c.cyan, nil)
Group.new("Typedef", c.yellow, nil)
Group.new("Special", c.purple, nil, s.bold)
Group.new("SpecialChar", c.purple, nil)
Group.new("Tag", c.blue, nil)
Group.new("Delimiter", c.superwhite, nil)
Group.new("SpecialComment", c.gray_medium, nil, s.bold)
Group.new("Underlined", c.blue, nil, s.underline)
Group.new("Error", c.red, c.gray0, s.bold)

