local builtin = require("telescope.builtin")

vim.keymap.set("n", "<space>pf", function()
	return builtin.find_files()
end)
vim.keymap.set("n", "<space>sg", function()
	return builtin.git_files { cwd = vim.fn.expand "%:h" }
end)
vim.keymap.set('n', '<leader>ws', function()
	local word = vim.fn.expand("<cword>")
	builtin.grep_string({ search = word })
end)
vim.keymap.set('n', '<leader>Ws', function()
	local word = vim.fn.expand("<cWORD>")
	builtin.grep_string({ search = word })
end)
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set("n", "<space>fh", builtin.help_tags)
vim.keymap.set("n", "<space>fm", builtin.man_pages)
vim.keymap.set("n", "<space>fo", builtin.oldfiles)
vim.keymap.set("n", "<space>fk", builtin.keymaps)
